const MOCK_STORES =[
  {
    "id": 1,
    "salon_name": "Lina Nails",
    "customer_name": "Mr Mike",
    "address": "8088 S 84th St, La Vista, NE 68128",
    "phone": "+14029373372",
    "sale_person": "Thuy Duyen",
    "marketing_person": "Hung - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=14vC7V6jA-8zo4NOSQyXteRj2Xbswg3Lq&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 2,
    "salon_name": "Vicky Nails Spa",
    "customer_name": "Ms Thuy",
    "address": "930 Old Monrovia Rd NW #8, Huntsville, AL 35806",
    "phone": "+12563264181",
    "sale_person": "Thuy Duyen",
    "marketing_person": "Hung - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1oQngHhcZC60UdjsbHG1Nlhv6F0n9Ouv7&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 3,
    "salon_name": "Star Nails & Spa",
    "customer_name": "Ms Kim Anh",
    "address": "102 Rembert C Dennis Blvd, Moncks Corner, SC 29461",
    "phone": "+18168019784",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hang - Hien",
    "marketing_person": "Hang - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1BAAJ8z6Aqx1ZZ5MoQaBlDkVjhig787mf&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 4,
    "salon_name": "Paris Nails",
    "customer_name": "Ms Uyen",
    "address": "1055 Mineral Wells Ave #9, Paris, TN 38242",
    "phone": "+17313361714",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hang - Hien",
    "marketing_person": "Hang - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1e0k9z4wV2DwuXrGGoLFiBBcIQWA552iX&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 5,
    "salon_name": "Canton Tic Tac Nails",
    "customer_name": "Hai Pham",
    "address": "42587 Ford Rd, Canton Township, MI 48187",
    "phone": "+17349347947",
    "sale_person": "Thuy Duyen",
    "marketing_person": "Hung - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=10gbl10lycPVUu4wompiScj2rJ97Wv00D&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 6,
    "salon_name": "Blue J Nails & Head Spa",
    "legal_name": "Blue J Nails & Head Spa",
    "customer_name": "Thuy Nguyen",
    "address": "1475 Bedford Hwy #2A, Bedford, NS B4A 3Z5, Canada",
    "phone": "+19023994477",
    "sale_person": "John Thai",
    "assigned_to": "Tuan - Hien",
    "marketing_person": "Tuan - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1iUWmnmakHykOge0OjUnHk7ABCBZcE70g&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 7,
    "salon_name": "U & Me Hair & Nails",
    "customer_name": "chưa có dữ liệu",
    "address": "2013 Tully Rd, San Jose, CA 95122",
    "phone": "+14086031784",
    "sale_person": "John Thai",
    "assigned_to": "Tuan - Hien",
    "marketing_person": "Tuan - Hien",
    "category": "Nail Salon",
    "notes": "mới tạo google nên không xuất report",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 8,
    "salon_name": "V.V. Nails and Spa",
    "customer_name": "Tung Le",
    "address": "4330 Centerplace Dr #613, Greeley, CO 80635",
    "phone": "+12398516850",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hang - Hien",
    "marketing_person": "Hang - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=18nhYKVnwtbHzcgQ_QCqBixLWF2Wb0f-w&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 9,
    "salon_name": "Sky Nails",
    "customer_name": "Pham Thi Cuc",
    "address": "1484 N State Rd 7, Lauderhill, FL 33313",
    "phone": "+19542574710",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hang - Hien",
    "marketing_person": "Hang - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1rwk3i8xNW_DnBfVoxcBOHQXpNQV-o9Y5&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 10,
    "salon_name": "Classy Nails",
    "customer_name": "Ms Dung",
    "address": "5270 Babcock St NE #12, Palm Bay, FL 32905",
    "phone": "+13214192245",
    "sale_person": "Thuy Duyen",
    "marketing_person": "Hung - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1L8hNo_OMwtUJOLndTHI2ZXbgf9_wFfMk&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 11,
    "salon_name": "Bamboo Nails & Spa",
    "customer_name": "Tammy Dung Nguyen",
    "address": "2711 La Frontera Blvd, Ste 205, Round Rock, TX 78681",
    "phone": "+14056266508",
    "sale_person": "Luci",
    "assigned_to": "Tuan - Hien",
    "marketing_person": "Tuan - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1kfN8zHPpvDn8wB-RXR4Rq5KsrZ4EClGW&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 12,
    "salon_name": "Nail Bar",
    "customer_name": "Nhung Le",
    "address": "7038 Highway 70 South, Nashville, TN 37221",
    "phone": "+16154238816",
    "sale_person": "My Duyen",
    "marketing_person": "Hung - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1nXVEA9neccHeu4euBiUGn3Q1u5oZ5Qoq&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 13,
    "salon_name": "Twinkle Nails & Spa",
    "customer_name": "Thanh Duong",
    "address": "3237 Yonge St, Toronto, ON M4N 2L5, Canada",
    "phone": "+16477183296",
    "sale_person": "John Thai",
    "assigned_to": "Hien - Hang",
    "marketing_person": "Hien - Hang",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1rdMv8E6bAqqUHU_aIQIBa0IbC8y1Oabh&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 14,
    "salon_name": "Salina Nail",
    "customer_name": "Linh Ngoc Bui",
    "address": "1489 County Rd 220 #150, Fleming Island, FL 32003",
    "phone": "+19046516731",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien - Tuan",
    "marketing_person": "Hien - Tuan",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1Smtm2kHP04ghqspEZLUAL0pk52jI2f1B&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 15,
    "salon_name": "King Nail Spa",
    "customer_name": "Thinh Vu Dong",
    "address": "7924 S Broadway Ave Ste 600, Tyler, TX 75703",
    "phone": "+19039448456",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien - Hang",
    "marketing_person": "Hien - Hang",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1LbbXT6eSuemHr37oPllrguSpJq1QMbPw&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 16,
    "salon_name": "Helen Nails & Spa",
    "customer_name": "Phong Hong Nguyen",
    "address": "1321 Fulton Ave, Sacramento, CA 95825",
    "phone": "+12099694203",
    "sale_person": "Luci",
    "assigned_to": "Hien - Tuan",
    "marketing_person": "Hien - Tuan",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 17,
    "salon_name": "Solar Deluxe Nails & Facial",
    "customer_name": "Tri Huu Pham",
    "address": "10400 S Post Oak, Suite B, Houston, TX 77035",
    "phone": "+12817458379",
    "sale_person": "Luci",
    "assigned_to": "Hien - Hung",
    "marketing_person": "Hien - Hung",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1ySHEs1s0xznCooPMelm98i1EP8w51JjR&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 18,
    "salon_name": "Eagle Nails",
    "customer_name": "Hua Y Pi",
    "address": "1700 Park Ave, Ste 104B, Park City, UT 84060",
    "phone": "+13852228122",
    "sale_person": "Dao",
    "assigned_to": "Hien - Hung",
    "marketing_person": "Hien - Hung",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1lKoYMC3h9YnFnBH8qG8NcpHBYadg6SwK&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 19,
    "salon_name": "Days Nails & Spa by XM",
    "customer_name": "Thi Xuan Pham",
    "address": "5140 Chattahoochee Ind Park, Cumming, GA 30041",
    "phone": "+14049605418",
    "sale_person": "Ruby",
    "assigned_to": "Hien",
    "marketing_person": "Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1EdU6pOxxyru4eO8k91ustHdvz6xAHY-G&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 20,
    "salon_name": "Star Nails & Spa",
    "customer_name": "Luat Thanh Nguyen",
    "address": "1416 Military Rd, Benton, AR 72015",
    "phone": "+15012498440",
    "sale_person": "Ngoc Anh",
    "assigned_to": "Hang - Hien",
    "marketing_person": "Hang - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1b7Dpp4VuvKnZwmuNtpiLg3K_8eU8zt6-&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 21,
    "salon_name": "Lumina Nails Lounge",
    "customer_name": "Phuc Hong Do",
    "address": "2526 S Campbell Ave, Springfield, MO 65807",
    "phone": "+14173504798",
    "sale_person": "Minh Anh",
    "assigned_to": "Hang - Hien",
    "marketing_person": "Hang - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1fD5D6dQo4ku3DGrmsuhcWG1NE340YU_f&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 22,
    "salon_name": "Nails Colure & Spa",
    "customer_name": "Nancy Le",
    "address": "2008 S Main St #304, Wake Forest, NC 27587",
    "phone": "+19194578719",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hang - Hien",
    "marketing_person": "Hang - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1UeiLhjoSv_AOL1-XUkx5PPhC2iq3rPjv&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 23,
    "salon_name": "J&M Nail Bar",
    "customer_name": "Ai Duc Hoang",
    "address": "11444 Hardin Valley Rd, Knoxville, TN 37932",
    "phone": "+18652666160",
    "sale_person": "Luci",
    "assigned_to": "Tuan - Hien",
    "marketing_person": "Tuan - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 24,
    "salon_name": "Morrissey Nails and Spa",
    "customer_name": "Vu Hoang Phung",
    "address": "960 Morrissey Blvd Space #6 & #7, Dorchester, MA 02122",
    "phone": "+16178881827",
    "sale_person": "John Thai",
    "assigned_to": "Hien - Tuan",
    "marketing_person": "Hien - Tuan",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=18RVGkhcovCY2adAovegaUVhZjQLsFRxD&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 25,
    "salon_name": "Image Nails",
    "customer_name": "John",
    "address": "139 N Belt Hwy Suite F, St Joseph, MO 64506",
    "phone": "+17015413140",
    "sale_person": "Truong",
    "assigned_to": "Hien - Hung",
    "marketing_person": "Hien - Hung",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1rnm-vL7prLfPWbvG8c_yGqg75hc7pFoc&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 26,
    "salon_name": "Fashion Nails and Spa",
    "customer_name": "Lien My Thi Tran",
    "address": "3441 E Causeway Approach Ste L, Mandeville, LA 70448",
    "phone": "+15043889102",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien - Tuan",
    "marketing_person": "Hien - Tuan",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1X0lVzTW-7YQIG6wqRCc4XilAK3xM5eQj&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 27,
    "salon_name": "The Nail Place Coppell LLC",
    "customer_name": "Le Thi Ngoc Oanh",
    "address": "230 N Denton Tap Rd, Ste 105, Coppell, TX 75019",
    "phone": "+12142284029",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien - Tuan",
    "marketing_person": "Hien - Tuan",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1LqtCeajvrT8CmxjfauJcG-AUdvyU7KZj&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 28,
    "salon_name": "Swan Nail",
    "customer_name": "Hai Anh - Thanh Thi Pham",
    "address": "4020 Hedgcoxe Rd #600, Plano, TX 75024",
    "phone": "+17372882991",
    "sale_person": "Yen Vuong",
    "assigned_to": "Hien - Hung",
    "marketing_person": "Hien - Hung",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1gq7XfId18X3VNWC0ZDLgax57Behxs3bY&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 29,
    "salon_name": "Antony Nails Bar",
    "customer_name": "Hien Nguyen",
    "address": "3710 E Main St Ste H, Blytheville, AR 72315",
    "phone": "+14697631113",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien - Hung",
    "marketing_person": "Hien - Hung",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 30,
    "salon_name": "Vip Nails Baytown",
    "customer_name": "Johnny Nguyen",
    "address": "508 Garth Rd F, Baytown, TX 77521, United States",
    "phone": "+18329082050",
    "sale_person": "John Thai",
    "assigned_to": "hằng - Hiển",
    "marketing_person": "Hang - Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 31,
    "salon_name": "IRIS NAILS FACIAL LLC",
    "customer_name": "ANH THI DUYEN NGUYEN ",
    "address": "3435 RAINTREE VILLAGE DR, KATY, TX 77449-7026",
    "phone": "+18322874690",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hien",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1Zq-0MwWq3SerGgUgC-wXEvGGAO15ZS5W&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 32,
    "salon_name": "Village Nails & Spa",
    "customer_name": "Mr Thương ",
    "address": "5618 Newbury St, Baltimore, MD 21209",
    "phone": "(443) 248-6082",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "https://drive.usercontent.google.com/u/0/uc?id=1FydscoyY41LAcNjM_fphPN8RePYh9I5i&export=download",
    "update": "07/09/2026"
  },
  {
    "id": 33,
    "salon_name": "Lucy Nails & Spa",
    "customer_name": "Mr Toản",
    "address": "973 East Ave, Chico, CA 95926",
    "phone": "(916) 837-7135",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 34,
    "salon_name": "Ann Nails",
    "customer_name": "Ms Ngoan",
    "address": "1523 N Texas Blvd, Weslaco, TX 78596",
    "phone": "",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 35,
    "salon_name": "Nail Spa Plus",
    "customer_name": "Nghĩa",
    "address": "764 Dennery Rd Ste 103, San Diego, CA 92154",
    "phone": "(858) 357-4941",
    "sale_person": "john thai",
    "assigned_to": "Hien",
    "marketing_person": "Hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 36,
    "salon_name": "Elegant Nails & Alterations",
    "customer_name": "Mr Tuấn",
    "address": "847 Park Rd C, Pleasant Grove, AL 35127",
    "phone": "(205) 370-4340",
    "sale_person": "thuy duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 37,
    "salon_name": "Apple nails and spa",
    "customer_name": "Mai Huynh",
    "address": "2340 SE Ocean Blvd, Stuart, FL 34996",
    "phone": "(772) 200-1227",
    "sale_person": "john thai",
    "assigned_to": "Hien",
    "marketing_person": "Hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 38,
    "salon_name": "Cutiecures Nail Bar",
    "customer_name": "Vy Nguyen",
    "address": "958 W El Camino Real, Sunnyvale, CA 94087",
    "phone": "408-649-1109",
    "sale_person": "Ngan",
    "assigned_to": "Hien",
    "marketing_person": "Hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 39,
    "salon_name": "Happy Nails",
    "customer_name": "Mrs Hương",
    "address": "613 Philadelphia Pike, Wilmington, DE 19809",
    "phone": "302 357 8628",
    "sale_person": "John Thai",
    "assigned_to": "Hien",
    "marketing_person": "Hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 40,
    "salon_name": "Tulip Nails",
    "customer_name": "Mr David",
    "address": "13864 Old Columbia Pike, Silver Spring, MD 20904",
    "phone": "(240) 708-5904",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 41,
    "salon_name": "Jenny's Nails",
    "customer_name": "NGOC EM",
    "address": "2617 Moses Grandy Trail #108, Chesapeake, VA 23323",
    "phone": "929-240-8855",
    "sale_person": "Thanh Tai",
    "assigned_to": "Hien",
    "marketing_person": "Hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 42,
    "salon_name": "Noodles N Boba",
    "customer_name": "Phúc Đặng",
    "address": "1975 Wells Rd, Orange Park, FL 32073, United States",
    "phone": "(407) 309-1423",
    "sale_person": "John Thai",
    "assigned_to": "Hien",
    "marketing_person": "Hùng - Hiển",
    "category": "Restaurant",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 43,
    "salon_name": "ELIZ'S NAILS",
    "customer_name": "MAI NGA NGUYEN T",
    "address": "7340 FOREST HILL AVE #D, RICHMOND VA 23225",
    "phone": "804-475-8151",
    "sale_person": "My Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 44,
    "salon_name": "Star nails and spa",
    "customer_name": "Thien Nguyen",
    "address": "1404 Berlin Tpke Wethersfield CT 06109",
    "phone": "(843) 301-1033",
    "sale_person": "Ngan",
    "assigned_to": "Hien",
    "marketing_person": "Hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 45,
    "salon_name": "OMA TATTOO",
    "customer_name": "THAO THANH BUI",
    "address": "10808 PRAIRIE HILLS DRIVE, OMAHA, NEBRASKA 68144",
    "phone": "(402) 802-7508",
    "sale_person": "Ngọc Anh",
    "assigned_to": "Hien",
    "marketing_person": "Hùng - Hiển",
    "category": "Tattoo",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 46,
    "salon_name": "Hiline Nail & Spa ",
    "customer_name": "Jessica Naylor",
    "address": "16561 Bolsa Chica St #104, Huntington CA 92649 ",
    "phone": "(714)-377-7999",
    "sale_person": "Ngan",
    "assigned_to": "Hien",
    "marketing_person": "Hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 47,
    "salon_name": "Cao Dung Day Spa ",
    "customer_name": "Loan",
    "address": "6799 Wilson Blvd # 7, Falls Church, VA 22044",
    "phone": "703-241-4143",
    "sale_person": "Tài",
    "assigned_to": "Hien",
    "marketing_person": "Hùng - Hiển",
    "category": "Beauty Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 48,
    "salon_name": "GENESIS NAIL SPA",
    "customer_name": "Loan",
    "address": "4880 Lower Roswell Rd Suite 470, Marietta, GA 30068",
    "phone": "770-354-1600",
    "sale_person": "MỸ DUYÊN",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 49,
    "salon_name": "Magic Nails & Spa",
    "customer_name": "Loan",
    "address": "419 Old Elkhart Rd, Palestine, TX 75801",
    "phone": "9034808707",
    "sale_person": "Thùy Duyên",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 50,
    "salon_name": "K2 Nails & Spa",
    "customer_name": "Ms Kim",
    "address": "96 Weaverville Rd Unit 101, Asheville, NC 28804",
    "phone": "8284506932",
    "sale_person": "Thùy Duyên",
    "assigned_to": "Hien",
    "marketing_person": "hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 51,
    "salon_name": "3 Little Bears / VH2 Precision Group",
    "customer_name": "Veon",
    "address": "no address",
    "phone": "(828) 216-9908",
    "sale_person": "Thùy Duyên",
    "assigned_to": "Hien",
    "marketing_person": "hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 52,
    "salon_name": "Lexington Nails",
    "customer_name": "Ms Diễm",
    "address": "734 W National Rd, Vandalia, OH 45377",
    "phone": "9377506808",
    "sale_person": "Thùy Duyên",
    "assigned_to": "Hien",
    "marketing_person": "hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 53,
    "salon_name": "L'Amour Nail Spa",
    "customer_name": "Mr Trường",
    "address": "1505 George Dieter Dr Ste 108, El Paso, TX 79936",
    "phone": "(808) 339-6489",
    "sale_person": "Thùy Duyên",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 54,
    "salon_name": "VIP Nails & Head Spa",
    "customer_name": "THOA THI KIM NGUYEN",
    "address": "1521 MILTON AVE, JANESVILLE, WI 53545",
    "phone": "(608) 580-2606",
    "sale_person": "Ngọc Anh",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 55,
    "salon_name": "Nails Plus",
    "customer_name": "Ms Suyla",
    "address": "3121 McClellan Blvd, Anniston, AL 36207",
    "phone": "9042405898",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 56,
    "salon_name": "CENTURY NAILS & SPA ",
    "customer_name": "HANG NGA THI DINH ",
    "address": "12119 LITTLE RD , HUDSON FL 34667",
    "phone": "(727) 254-9147",
    "sale_person": "Ngọc Anh",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 57,
    "salon_name": "Nail Care Athens",
    "customer_name": "SUONG LE",
    "address": "120 Alps Rd, Athens, GA 30606",
    "phone": "(678) 575-6436",
    "sale_person": "NGÂN",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 58,
    "salon_name": "Sunflower Nails",
    "customer_name": "Ms Tú",
    "address": "3930 A St SE #306, Auburn, WA 98002",
    "phone": "2063802998",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 59,
    "salon_name": "CRYSTAL NAILS",
    "customer_name": "GIAU THI LE",
    "address": "3141 FM 528 SUITE 300 , FRIENDSWOOD TX 77546",
    "phone": "281-716-0663",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 60,
    "salon_name": "Lee Midtown Salon",
    "customer_name": "GIAU THI LE",
    "address": "1485 S Wells Ave, Reno, NV 89502",
    "phone": "281-716-0663",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 61,
    "salon_name": "Young Nail & Spa",
    "customer_name": "KIEU NGOC XUAN TRAN",
    "address": "322 E Shaw Ave, Fresno, CA 93710",
    "phone": "(559) 394-8160",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "Hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 62,
    "salon_name": "Glossy Nails",
    "customer_name": "Ms Hiền",
    "address": "1056 Goodman Rd E, Southaven, MS 38671",
    "phone": "(901) 336-7008",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hiển-Hùng",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 63,
    "salon_name": "ROSE'S NAILS & SPA",
    "customer_name": "Nancy",
    "address": "1209 Flammang Dr, Waterloo, IA 50702",
    "phone": "(712) 444-3066",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 64,
    "salon_name": "INKNITY TATTOO",
    "customer_name": "Nghĩa",
    "address": "7701 SHARON LAKES RD, CHARLOTTE, NC 28210",
    "phone": "(980) 613-2139",
    "sale_person": "Ngoc Anh",
    "assigned_to": "Hien",
    "marketing_person": "Hiển",
    "category": "Tatoo Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 65,
    "salon_name": "Modern Nails & Spa",
    "customer_name": "",
    "address": "3825 University Ave, Waterloo, IA 50701",
    "phone": "(980) 613-2139",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "Văn - Ngân",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 66,
    "salon_name": "Diva Nails & Spa",
    "customer_name": "Mỹ",
    "address": "6 Bank St, Nitro, WV 25143, United States",
    "phone": "(681) 417-9617",
    "sale_person": "John Thai",
    "assigned_to": "Hien",
    "marketing_person": "hằng-hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 67,
    "salon_name": "GORGEOUS NAILS",
    "customer_name": "ALICIA CHAU NGUYEN",
    "address": "27327 23 Mile Rd, Chesterfield, MI 48051",
    "phone": "586-329-1993",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "hằng-hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 68,
    "salon_name": "Judy Nails Spa Lashes",
    "customer_name": "Diem Truong",
    "address": "2428 Southmore Ave, Pasadena, TX 77502",
    "phone": "(832) 274-0313",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 69,
    "salon_name": "Andy Nail Spa ",
    "customer_name": "Diệu",
    "address": "4467 Mission St, San Francisco, CA 94112",
    "phone": "(415) 335-0671",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 70,
    "salon_name": "315 Pedi N Nails ",
    "customer_name": "Van Dang",
    "address": "315 Lincoln Rd unit 9, Waterloo, ON N2J 4H7",
    "phone": "(226) 505-4783",
    "sale_person": "John Thai",
    "assigned_to": "Hien",
    "marketing_person": "hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 71,
    "salon_name": "Shine Nail Art",
    "customer_name": "Ms Anh",
    "address": "7941 Beach Blvd C, Buena Park, CA 90620",
    "phone": "(714) 710-2168",
    "sale_person": "Dino",
    "assigned_to": "Hien",
    "marketing_person": "hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 72,
    "salon_name": "Cutiecures Nail Bar",
    "customer_name": "Vy Nguyen",
    "address": "958 W El Camino Real, Sunnyvale, CA 94087",
    "phone": "408-649-1109",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 73,
    "salon_name": "Happy Nails Day Spa",
    "customer_name": "ms lisa",
    "address": "2213 & 2217 Defense Highway Crofton, MD 21114",
    "phone": "(240) 688-5176",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 74,
    "salon_name": "Davie nails & spa",
    "customer_name": "Man Van",
    "address": "4700 S Flamingo Rd Cooper City FL 33330",
    "phone": "954 305 0046",
    "sale_person": "John Thai",
    "assigned_to": "Hien",
    "marketing_person": "hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 75,
    "salon_name": "Diva Nails & Spa",
    "customer_name": "Chị Ny",
    "address": "6 Bank St, Nitro, WV 25143, United States",
    "phone": "(815) 582-7322",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "Hằng",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 76,
    "salon_name": "Bamboo House",
    "customer_name": "mr điền",
    "address": "413 N Main St, Bonham, TX 75418",
    "phone": "(815) 582-7322",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hằng- Hiển",
    "category": "Restaurant",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 77,
    "salon_name": "Paris House",
    "customer_name": "mr điền",
    "address": "7 E Plaza, Paris, TX 75460",
    "phone": "(469) 545-8805",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hằng- Hiển",
    "category": "Restaurant",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 78,
    "salon_name": "New Boston House",
    "customer_name": "mr điền",
    "address": "129 NE Front St, New Boston, TX 75570, United States",
    "phone": "(469) 545-8805",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hằng- Hiển",
    "category": "Restaurant",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 79,
    "salon_name": "Real Nails & Spa",
    "customer_name": "Khang V Banh",
    "address": "189 N Park Blvd, Lake Orion, MI 48362",
    "phone": "(248) 690-7279",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "Hằng- Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 80,
    "salon_name": "Central Nails",
    "customer_name": "Ms Mandy",
    "address": "10216 Curry Ford Rd, Orlando, FL 32825",
    "phone": "(407) 724-3879",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Ngân",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 81,
    "salon_name": "Extra nails",
    "customer_name": "Tuyet Phuong Tsan",
    "address": "3364 Chamblee Tucker Rd B, Chamblee, GA 30341",
    "phone": "(470) 929-9372",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 82,
    "salon_name": "Eric Nails & Spa",
    "customer_name": "Huong",
    "address": "6330 Florin Rd, Sacramento, CA 95823",
    "phone": "9164791072",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "hùng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 83,
    "salon_name": "Kissie Nails & Spa",
    "customer_name": "Khue Nguyen",
    "address": "11318 S orange blossom trl. Orlando Fl 32837",
    "phone": "(407) 779-0151",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "hằng - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 84,
    "salon_name": "HV NAIL STUDIO ",
    "customer_name": "anna",
    "address": "10606 E 96th St, Fishers, IN 46037",
    "phone": "(317) 416-8007",
    "sale_person": "Ngân",
    "assigned_to": "Hien",
    "marketing_person": "Loan - Hiển",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 85,
    "salon_name": "Best City Nails",
    "customer_name": "Wendy",
    "address": "74520 CA-111 Ste B2, Palm Desert, CA 92260",
    "phone": "(317) 416-8007",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "mimi",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 86,
    "salon_name": "Heavenly Beauty Salon",
    "customer_name": "Ms Phượng",
    "address": "1507 23RD ST San Pablo CA 94806",
    "phone": "5107074007",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "mimi",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 87,
    "salon_name": "Judy Hair & Nails",
    "customer_name": "Ms Judy",
    "address": "1112 University Ave, Berkeley, CA 94702",
    "phone": "510-666-0755",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "mimi",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 88,
    "salon_name": "Pro nails & Spa",
    "customer_name": "Ms Alex",
    "address": "719 N 114th St, Omaha, NE 68154",
    "phone": "402-991-7989",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Ngan",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 89,
    "salon_name": "Miss Nails",
    "customer_name": "",
    "address": "1236 Guilford College Rd #109, Jamestown, NC 27282",
    "phone": "",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hung",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 90,
    "salon_name": "Holly Nails & Spa",
    "customer_name": "Chi Chau",
    "address": "2316 Dell Range Blvd b1, Cheyenne, WY 82009",
    "phone": "(307) 214-6686",
    "sale_person": "Ngan",
    "assigned_to": "",
    "marketing_person": "Mi Mi",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 91,
    "salon_name": "Harmony Nails & Head Spa",
    "customer_name": "Ms Michelle",
    "address": "",
    "phone": "",
    "sale_person": "Thuy Duyen",
    "assigned_to": "",
    "marketing_person": "Ngan",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 92,
    "salon_name": "Long Nails and Spa",
    "customer_name": "Long",
    "address": "1600 Shorter Ave NW, Rome, GA 30165",
    "phone": "762-420-6309",
    "sale_person": "Thuy Duyen",
    "assigned_to": "",
    "marketing_person": "Mi Mi",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 93,
    "salon_name": "LILYPAD SPA",
    "customer_name": "Ms Hannah",
    "address": "369 Bay St, San Francisco, CA 94133",
    "phone": "(415) 746-0931",
    "sale_person": "Dino",
    "assigned_to": "",
    "marketing_person": "Ngan",
    "category": "Spa",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 94,
    "salon_name": "SALON 352 NAILS BY CHRISTY",
    "customer_name": "Ms Vivian",
    "address": "2124 Mariner Blvd. Spring Hill, FL 34609",
    "phone": "7274580741",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hang",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 95,
    "salon_name": "Canton Tic Tac Nails",
    "customer_name": "Hai Pham",
    "address": "42587 Ford Rd, Canton Township, MI 48187",
    "phone": "734-934-7947",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hung",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 96,
    "salon_name": "MAD CRAB",
    "customer_name": "An",
    "address": "12490 St Charles Rock Rd, Bridgeton, MO 63044, United States",
    "phone": "(314) 715-1013",
    "sale_person": "Minh Anh",
    "assigned_to": "",
    "marketing_person": "Mi Mi",
    "category": "Restaurant",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 97,
    "salon_name": "Zen's Nails",
    "customer_name": "Ms Thanh",
    "address": "205 Burnside Ave, East Hartford, CT 06108",
    "phone": "",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hung",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 98,
    "salon_name": "Zen’s Nails & Spa",
    "customer_name": "Ms Thanh",
    "address": "312 Hartford Turnpike, Vernon, CT 06066",
    "phone": "(860) 871-9806",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hung",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 99,
    "salon_name": "Glam Nails",
    "customer_name": "",
    "address": "876 W Street Rd, Warminster Township, PA 18974",
    "phone": "",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Ngan",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 100,
    "salon_name": "Red Persimmon Nail",
    "customer_name": "Mr Duy",
    "address": "27939 Seco Canyon Rd, Santa Clarita, CA 91350",
    "phone": "(661) 296-3789",
    "sale_person": "Thuy Duyen",
    "assigned_to": "",
    "marketing_person": "Mi Mi",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 101,
    "salon_name": "Lumina Nails Lounge",
    "customer_name": "Patrick Nguyen Le",
    "address": "5445 20th St #105, Vero Beach, FL 32966",
    "phone": "267-285-3423",
    "sale_person": "Ngan",
    "assigned_to": "Hien",
    "marketing_person": "Ngan",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 102,
    "salon_name": "Noodles N Boba",
    "customer_name": "Phuc Dang",
    "address": "1975 Wells Rd, Orange Park, FL 32073, United States",
    "phone": "(407) 309-1423",
    "sale_person": "John",
    "assigned_to": "",
    "marketing_person": "Hung",
    "category": "Restaurant",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 103,
    "salon_name": "Sky Nails",
    "customer_name": "Pham Thi Cuc",
    "address": "1484 N State Rd 7, Lauderhill, FL 33313",
    "phone": "(954)-257-4710",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hang",
    "category": "Nail Salon",
    "notes": "",
    "link": "",
    "update": "07/09/2026"
  },
  {
    "id": 104,
    "salon_name": "Fancy Nails",
    "customer_name": "Ms Michelle",
    "address": "3316 Williams Blvd, Kenner, LA 70065",
    "phone": "",
    "sale_person": "Thuy Duyen",
    "assigned_to": "",
    "marketing_person": "",
    "category": "Nail Salon",
    "update": "07/09/2026"
  },
  {
    "id": 105,
    "salon_name": "NAILS BARS",
    "customer_name": "OANH",
    "address": "",
    "phone": "",
    "sale_person": "Dino",
    "assigned_to": "Hien",
    "marketing_person": "Hung",
    "category": "Nail Salon",
    "update": "07/09/2026"
  },
  {
    "id": 106,
    "salon_name": "Le Nails",
    "customer_name": "Ms Hương",
    "address": "1650 Starlite Dr, Owensboro, KY 42301",
    "phone": "",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Ngan",
    "marketing_person": "",
    "category": "Nail Salon",
    "update": "07/09/2026"
  },
  {
    "id": 107,
    "salon_name": "Star Nails & Spa",
    "customer_name": "Ms Kim Anh",
    "address": "102 Rembert C Dennis Blvd, Moncks Corner, SC 29461",
    "phone": "(816) 801-9784",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hang",
    "category": "Nail Salon",
    "update": "07/09/2026"
  },
  {
    "id": 108,
    "salon_name": "NAILS BARS",
    "customer_name": "OANH",
    "address": "",
    "phone": "",
    "sale_person": "Dino",
    "assigned_to": "",
    "marketing_person": "",
    "category": "Nail Salon",
    "update": "07/09/2026"
  },
  {
    "id": 109,
    "salon_name": "STAR NAILS & SPA",
    "customer_name": "Luat Thanh Nguyen",
    "address": "1416 Military Rd, Benton, AR 72015",
    "phone": "(501) 249-8440 / 501-315-2344",
    "sale_person": "Ngoc Anh",
    "assigned_to": "Hien",
    "marketing_person": "Hang",
    "category": "Nail Salon",
    "update": "07/09/2026"
  },
  {
    "id": 110,
    "salon_name": "Beauty Wellness",
    "customer_name": "Ms Hồng",
    "address": "5549 Hwy 6 N, Houston, TX 77084, United States",
    "phone": "(713) 269-6129",
    "sale_person": "John",
    "assigned_to": "Ngan",
    "marketing_person": "",
    "category": "Beauty Salon",
    "update": "07/09/2026"
  },
  {
    "id": 111,
    "salon_name": "Nail Fever & Spa",
    "customer_name": "Mr Alex",
    "address": "6878 E Sunrise Dr, Tucson, AZ 85750",
    "phone": "",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Mimi",
    "marketing_person": "",
    "category": "Nail Salon",
    "update": "07/09/2026"
  },
  {
    "id": 112,
    "salon_name": "VIP Nails LLC",
    "customer_name": "Ms Jenifer",
    "address": "6730 Lone Tree Wy #1, Brentwood, CA 94513",
    "phone": "",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hien",
    "marketing_person": "Hung",
    "category": "Nail Salon",
    "update": "07/09/2026"
  },
  {
    "id": 113,
    "salon_name": "M-Sleek nail",
    "customer_name": "Chị Michelle",
    "address": "584 S Murphy Ave, Sunnyvale, CA 94086",
    "phone": "(408) 910-9595",
    "sale_person": "Ngan",
    "assigned_to": "Hien",
    "marketing_person": "Hang",
    "category": "Nail Salon",
    "update": "07/09/2026"
  },
  {
    "id": 114,
    "salon_name": "DAYS NAILS & SPA BY XM",
    "customer_name": "Thi Xuan Pham",
    "address": "5140 Chattahoochee Ind Park, Cumming, GA 30041",
    "phone": "(404) 960-5418",
    "sale_person": "Ruby",
    "assigned_to": "Hang",
    "marketing_person": "",
    "category": "Nail Salon",
    "update": "07/09/2026"
  },
  {
    "id": 115,
    "salon_name": "Hair No 1",
    "customer_name": "Tonu Dương",
    "address": "975 Manor Blvd, San Leandro, CA 94579",
    "phone": "Manager: (415) 740-1337 / Chủ: (510) 287-6417",
    "sale_person": "Ngan",
    "assigned_to": "Loan",
    "marketing_person": "",
    "category": "Hair Salon",
    "update": "07/09/2026"
  },
  {
    "id": 116,
    "salon_name": "VIP NAILS LOVE",
    "customer_name": "THANH KIM NGUYEN",
    "address": "1964 E OSCEOLA PKWY, KISSIMMEE, FL 347433",
    "phone": "407-837-0943",
    "sale_person": "Thuy Duyen",
    "assigned_to": "",
    "marketing_person": "",
    "category": "Nail Salon",
    "update": "07/09/2026"
  },
  {
    "id": 117,
    "salon_name": "V.v. Nails and Spa",
    "customer_name": "Tung Le",
    "address": "4330 Centerplace Dr #613, Greeley, CO 806345",
    "phone": "239-851-6850",
    "sale_person": "Thuy Duyen",
    "assigned_to": "Hang",
    "marketing_person": "",
    "category": "Nail Salon",
    "update": "07/09/2026"
  }
]
